/*
 * libcedar.h — C bindings for the Cedar policy engine
 *
 * This header is auto-generated by cbindgen. Do not edit manually.
 *
 * Usage:
 *   #include "libcedar.h"
 *   CedarEngine *engine = cedar_engine_new();
 *   cedar_engine_set_policies(engine, "permit(...);");
 *   CedarDecision d = cedar_engine_is_authorized(engine, ...);
 *   cedar_engine_free(engine);
 */


#ifndef LIBCEDAR_H
#define LIBCEDAR_H

/* Generated with cbindgen:0.27.0 */

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Decision returned by `cedar_engine_is_authorized`.
//
// - `Allow  = 0`
// - `Deny   = 1`
// - `Error  = -1` (query could not be evaluated; check `cedar_engine_last_error`)
typedef enum CedarDecision {
    Allow = 0,
    Deny = 1,
    Error = -1,
} CedarDecision;

// Opaque engine handle. Never exposed to C directly — only via `*mut CedarEngine`.
typedef struct CedarEngine CedarEngine;

// Create a new Cedar engine.
//
// Returns an opaque pointer. The caller **must** eventually call
// `cedar_engine_free` to release the memory.
//
// Returns `NULL` on allocation failure (should never happen in practice).
struct CedarEngine *cedar_engine_new(void);

// Destroy a Cedar engine and free all associated memory.
//
// Passing `NULL` is safe (no-op).
void cedar_engine_free(struct CedarEngine *engine);

// Load Cedar policies from a policy text string (Cedar syntax).
//
// The existing policy set is **replaced** entirely.
//
// # Returns
// - `0` on success
// - `-1` on error (call `cedar_engine_last_error` for details)
int32_t cedar_engine_set_policies(struct CedarEngine *engine, const char *policies_text);

// Add (append) Cedar policies from a policy text string.
//
// Unlike `cedar_engine_set_policies`, this does **not** replace existing
// policies — the new policies are merged into the current set by
// re-parsing the combined policy text.
//
// # Returns
// - The number of new policies added on success (>= 0)
// - `-1` on error
int32_t cedar_engine_add_policies(struct CedarEngine *engine, const char *policies_text);

// Set the Cedar schema from a JSON string.
//
// The schema is used for request validation and entity parsing.
// Pass `NULL` to clear the schema.
//
// # Returns
// - `0` on success
// - `-1` on error
int32_t cedar_engine_set_schema_json(struct CedarEngine *engine, const char *schema_json);

// Set the entity store from a JSON string (Cedar entity JSON format).
//
// The existing entity store is **replaced** entirely.
//
// # Returns
// - `0` on success
// - `-1` on error
int32_t cedar_engine_set_entities_json(struct CedarEngine *engine, const char *entities_json);

// Clear all entities from the store.
void cedar_engine_clear_entities(struct CedarEngine *engine);

// Evaluate an authorization request.
//
// All string parameters use Cedar entity UID syntax:
// - `principal`: e.g. `User::"alice"` or `MyApp::User::"alice"`
// - `action`:    e.g. `Action::"SELECT"` or `MyApp::Action::"view"`
// - `resource`:  e.g. `Table::"public.employees"`
// - `context_json`: JSON object for the request context, or `NULL` for empty context
//
// # Returns
// - `CedarDecision::Allow` (0) if the request is allowed
// - `CedarDecision::Deny` (1) if the request is denied
// - `CedarDecision::Error` (-1) if the request could not be evaluated
enum CedarDecision cedar_engine_is_authorized(struct CedarEngine *engine,
                                              const char *principal,
                                              const char *action,
                                              const char *resource,
                                              const char *context_json);

// Evaluate an authorization request without materializing diagnostics.
//
// This is intended for hot paths that only care about the allow/deny result and
// will inspect `cedar_engine_last_error()` only when the return value is `Error`.
// On successful evaluations the previous error/diagnostics state is left untouched
// to avoid mutating the engine on every request.
enum CedarDecision cedar_engine_is_authorized_no_diagnostics(struct CedarEngine *engine,
                                                             const char *principal,
                                                             const char *action,
                                                             const char *resource,
                                                             const char *context_json);

// Get the last error message.
//
// Returns a pointer to a null-terminated C string, or `NULL` if no error is set.
// The pointer is valid until the next call to any `cedar_engine_*` function on
// the same engine.
const char *cedar_engine_last_error(const struct CedarEngine *engine);

// Clear the last error.
void cedar_engine_clear_error(struct CedarEngine *engine);

// Get diagnostics from the last `cedar_engine_is_authorized` call.
//
// Returns a pointer to a null-terminated JSON string containing `reasons`
// and `errors` arrays, or `NULL` if no authorization has been performed.
//
// Example output: `{"reasons":["policy0"],"errors":[]}`
//
// The pointer is valid until the next call to `cedar_engine_is_authorized`
// or `cedar_engine_free`.
const char *cedar_engine_get_diagnostics(const struct CedarEngine *engine);

// Validate the current policy set against the loaded schema.
//
// # Returns
// - `0` if validation passes (or no schema is loaded)
// - `-1` if validation fails (call `cedar_engine_last_error` for details)
int32_t cedar_engine_validate(struct CedarEngine *engine);

#endif  /* LIBCEDAR_H */
